version: '3.3'

services: 

    api_outlet:
        build:
            context: .
        volumes:
            - ./api_outlet:/api_outlet
            - /api_outlet/node_modules
        ports:
            - 5000:8000

        command: 
            sh -c "node api_outlet/server.js"


    selenium:
        image: selenium/standalone-chrome
        ports:
        - 4444:4444
        restart: always



    app:
        build: 
            context: .
        volumes: 
            - ./app:/app
        depends_on: 
            - selenium
            - api_outlet

