version: '3.3'

services: 


    
    selenium:
        image: selenium/standalone-chrome
        ports:
        - 4444:4444
        restart: always


    api_outlet:
        build:
            context: .
        restart: 
            always
        volumes:
            - ./api_outlet:/api_outlet
            - /api_outlet/node_modules
        ports:
            - 5000:8000

        command: 
            sh -c "node api_outlet/server.js"





    # app:
    #     build: 
    #         context: .
    #     volumes: 
    #         - ./app:/app
    #     environment: 
    #         - PYTHONUNBUFFERED:1
    #     command:
    #         sh -c "python3 ./app/source.py this"
    #     depends_on: 
    #         - selenium
    #         - api_outlet

