version: '3.3'

services: 

    selenium:
        image: selenium/standalone-chrome
        # image: selenium/hub
        
        ports:
        - 4444:4444
        restart: always
        # environment:
        #     - SE_OPTS=-debug
        #     - GRID_MAX_SESSION=20
        #     - GRID_BROWSER_TIMEOUT=10000
        #     - GRID_TIMEOUT=10000

    api_outlet:
        build:
            context: .
        restart: 
            always
        volumes:
            - ./api_outlet:/api_outlet
            - /api_outlet/node_modules
        ports:
            - 5000:8000

        command: 
            sh -c "node api_outlet/server.js"
        
    # chrome:
    #     image: selenium/node-chrome
    #     depends_on:
    #         - selenium_hub
    #     environment: 
    #         - NODE_MAX_SESSION=20
    #         - NODE_MAX_INSTANCES=20
    #         - HUB_HOST=selenium_hub
    #         - HUB_PORT=4444

        # capabilities: [
        #     {
        #         browserName: 'chrome',
        #         'goog:chromeOptions': {
        #         args: [
        #             '--no-sandbox',
        #             '--disable-dev-shm-usage',
        #             '--disable-gpu',
        #             '--window-size=1920,1080'
        #         ]
        #         }
        #     }
        #     ...
        #     ]


    # app:
    #     build: 
    #         context: .
    #     volumes: 
    #         - ./app:/app
    #     environment: 
    #         - PYTHONUNBUFFERED:1
    #     command:
    #         sh -c "python3 ./app/source.py this"
    #     depends_on: 
    #         - selenium
    #         - api_outlet

